application: quaxelrodspot 
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

builtins:
- remote_api: on
- appstats: on
- datastore_admin: on


handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images


- url: /static
  static_dir: static


- url: .*
  script: main.py

